import { LegalPageLayout } from '@/components/legal-page-layout'

export default function CGUPage() {
  return (
    <LegalPageLayout
      title="Conditions Générales d'Utilisation"
      description="Modalités d'utilisation des services Xeyo, droits et obligations des utilisateurs."
      lastUpdated="1 mai 2026"
      titleEn="Terms of Use"
      descriptionEn="Terms of use of Xeyo services, rights and obligations of users."
      lastUpdatedEn="May 1, 2026"
      childrenEn={
        <>
          <h2>Article 1 – Purpose</h2>
          <p>
            These Terms of Use (ToU) define the terms and conditions for using the services
            offered by Xeyo, as well as the rights and obligations of users.
          </p>
          <p>
            Registration for and use of the Services imply full and unreserved acceptance of these ToU.
          </p>

          <h2>Article 2 – Description of the Services</h2>
          <p>Xeyo offers a SaaS platform enabling:</p>
          <ul>
            <li>Connecting WhatsApp accounts (personal or business)</li>
            <li>Automating replies through artificial intelligence agents</li>
            <li>Centralized management of WhatsApp conversations</li>
            <li>Collaborative team management</li>
            <li>Tracking and analysis of conversations</li>
          </ul>

          <h2>Article 3 – Access to the Services</h2>

          <h3>3.1 Registration</h3>
          <p>
            Access to the Services requires the creation of a user account. The User undertakes to provide
            accurate and up-to-date information. The User must be at least 18 years old and have the legal
            capacity to enter into a contract.
          </p>

          <h3>3.2 Access levels</h3>
          <p>Access to the platform&apos;s features is conditional upon the status of the account:</p>
          <ul>
            <li>Account created without payment: access to the pricing page only, no feature available</li>
            <li>Setup deposit paid (€445): access to the onboarding configurator only</li>
            <li>Setup balance paid (€445) or active self-service subscription: full access to the features of the subscribed plan</li>
          </ul>

          <h3>3.3 Credentials</h3>
          <p>
            The User is responsible for the confidentiality of their login credentials. Any use
            from their account is deemed to have been made by them.
          </p>
          <p>
            In the event of fraudulent use, the User must inform Xeyo immediately:{' '}
            <a href="mailto:contact@autyvia.fr">contact@autyvia.fr</a>
          </p>

          <h2>Article 4 – Use of the Services</h2>

          <h3>4.1 Permitted uses</h3>
          <p>
            The Services are intended for professional use to automate and manage WhatsApp
            communications within the scope of a legitimate commercial activity.
          </p>

          <h3>4.2 Prohibited uses</h3>
          <p>The User undertakes in particular not to:</p>
          <ul>
            <li>Use the Services for illegal or fraudulent purposes</li>
            <li>Send unsolicited messages (spam)</li>
            <li>Impersonate a third party</li>
            <li>Collect personal data without consent</li>
            <li>Distribute unlawful, defamatory, hateful, or pornographic content</li>
            <li>Attempt to circumvent security measures</li>
            <li>Violate WhatsApp&apos;s terms of use</li>
            <li>Resell or sublicense access to the Services</li>
          </ul>

          <h2>Article 5 – Artificial intelligence</h2>
          <p>
            The User acknowledges that responses generated by the AI may contain errors. They remain
            responsible for the messages sent from their WhatsApp account and must supervise and properly configure
            their AI agents. Xeyo does not guarantee the accuracy of the generated responses.
          </p>
          <p>
            A customer who configures the platform themselves without Xeyo support (self-service path) is solely
            responsible for the results obtained. Xeyo cannot be held liable for incorrect self-configuration.
          </p>

          <h2>Article 6 – WhatsApp connection and Meta responsibility</h2>
          <p>The User acknowledges and accepts that:</p>
          <ul>
            <li>The connection of their WhatsApp account to Xeyo is carried out via the official WhatsApp Business API (Meta Cloud API)</li>
            <li>Use of WhatsApp remains subject to Meta/WhatsApp&apos;s Terms of Use</li>
            <li>Meta/WhatsApp may at any time suspend or close an account in the event of a violation of its rules</li>
            <li>Sending automated messages, spam, or unsolicited content may result in the WhatsApp account being banned by Meta</li>
          </ul>

          <p>The User undertakes to:</p>
          <ul>
            <li>Comply with the WhatsApp Business Terms of Use</li>
            <li>Not use the Services to send unsolicited messages (spam)</li>
            <li>Obtain the prior consent of recipients for automated communications</li>
            <li>Comply with the message volume limits imposed by WhatsApp</li>
          </ul>

          <div className="not-prose my-4 rounded-lg border-l-4 border-red-500 bg-red-50 p-4 dark:bg-red-950/30">
            <p className="font-medium text-slate-900 dark:text-white">Disclaimer</p>
            <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">
              Xeyo cannot be held liable for the suspension, limitation, or closure of a WhatsApp
              account by Meta, for any reason whatsoever. No refund will be issued in such a case.
            </p>
          </div>

          <h2>Article 7 – Intellectual property</h2>
          <p>Xeyo retains all intellectual property rights in the Services.</p>
          <p>The User retains all rights to the content they create or upload.</p>

          <h2>Article 8 – Liability</h2>
          <p>Xeyo undertakes to provide the Services with due diligence (best-efforts obligation).</p>
          <p>Xeyo cannot be held liable for:</p>
          <ul>
            <li>Service interruptions beyond its control</li>
            <li>Content generated by artificial intelligence</li>
            <li>The suspension or closure of WhatsApp accounts by Meta</li>
            <li>Indirect damages (loss of revenue, etc.)</li>
            <li>Results obtained within a self-service path without support</li>
          </ul>

          <h2>Article 9 – Suspension, termination, and data</h2>
          <p>
            Xeyo may suspend or terminate access to the Services, without notice, in the event of a violation of these
            ToU, fraudulent or abusive use, non-payment, or a request from the competent authorities.
          </p>
          <p>
            Upon termination or permanent suspension, the customer&apos;s data (conversations, agents, documents, knowledge
            base) is retained for 30 days, then permanently deleted in accordance with the GDPR.
            No recovery is possible after this period.
          </p>

          <h2>Article 10 – Applicable law</h2>
          <p>These ToU are governed by French law.</p>
          <p>
            In the event of a dispute, the parties shall seek an amicable solution. Failing this, the French courts
            shall have jurisdiction.
          </p>
        </>
      }
    >
      <h2>Article 1 – Objet</h2>
      <p>
        Les présentes Conditions Générales d&apos;Utilisation (CGU) définissent les modalités d&apos;utilisation des services
        proposés par Xeyo, ainsi que les droits et obligations des utilisateurs.
      </p>
      <p>
        L&apos;inscription et l&apos;utilisation des Services impliquent l&apos;acceptation pleine et entière des présentes CGU.
      </p>

      <h2>Article 2 – Description des Services</h2>
      <p>Xeyo propose une plateforme SaaS permettant :</p>
      <ul>
        <li>La connexion de comptes WhatsApp (personnel ou business)</li>
        <li>L&apos;automatisation des réponses via des agents d&apos;intelligence artificielle</li>
        <li>La gestion centralisée des conversations WhatsApp</li>
        <li>La gestion collaborative en équipe</li>
        <li>Le suivi et l&apos;analyse des conversations</li>
      </ul>

      <h2>Article 3 – Accès aux Services</h2>

      <h3>3.1 Inscription</h3>
      <p>
        L&apos;accès aux Services nécessite la création d&apos;un compte utilisateur. L&apos;Utilisateur s&apos;engage à fournir
        des informations exactes et à jour. L&apos;Utilisateur doit être âgé d&apos;au moins 18 ans et avoir la capacité
        juridique de contracter.
      </p>

      <h3>3.2 Niveaux d&apos;accès</h3>
      <p>L&apos;accès aux fonctionnalités de la plateforme est conditionné au statut du compte :</p>
      <ul>
        <li>Compte créé sans paiement : accès à la page tarifaire uniquement, aucune fonctionnalité disponible</li>
        <li>Acompte de mise en place payé (445 €) : accès au configurateur d&apos;onboarding uniquement</li>
        <li>Solde de mise en place payé (445 €) ou abonnement self-service actif : accès complet aux fonctionnalités de la gamme souscrite</li>
      </ul>

      <h3>3.3 Identifiants</h3>
      <p>
        L&apos;Utilisateur est responsable de la confidentialité de ses identifiants de connexion. Toute utilisation
        depuis son compte est réputée avoir été faite par lui.
      </p>
      <p>
        En cas d&apos;utilisation frauduleuse, l&apos;Utilisateur doit informer Xeyo immédiatement :{' '}
        <a href="mailto:contact@autyvia.fr">contact@autyvia.fr</a>
      </p>

      <h2>Article 4 – Utilisation des Services</h2>

      <h3>4.1 Usages autorisés</h3>
      <p>
        Les Services sont destinés à un usage professionnel pour automatiser et gérer les communications
        WhatsApp dans le cadre d&apos;une activité commerciale légitime.
      </p>

      <h3>4.2 Usages interdits</h3>
      <p>L&apos;Utilisateur s&apos;interdit notamment de :</p>
      <ul>
        <li>Utiliser les Services à des fins illégales ou frauduleuses</li>
        <li>Envoyer des messages non sollicités (spam)</li>
        <li>Usurper l&apos;identité d&apos;un tiers</li>
        <li>Collecter des données personnelles sans consentement</li>
        <li>Diffuser des contenus illicites, diffamatoires, haineux ou pornographiques</li>
        <li>Tenter de contourner les mesures de sécurité</li>
        <li>Violer les conditions d&apos;utilisation de WhatsApp</li>
        <li>Revendre ou sous-licencier l&apos;accès aux Services</li>
      </ul>

      <h2>Article 5 – Intelligence artificielle</h2>
      <p>
        L&apos;Utilisateur reconnaît que les réponses générées par l&apos;IA peuvent contenir des erreurs. Il reste
        responsable des messages envoyés depuis son compte WhatsApp et doit superviser et paramétrer correctement
        ses agents IA. Xeyo ne garantit pas l&apos;exactitude des réponses générées.
      </p>
      <p>
        Le client configurant lui-même la plateforme sans accompagnement Xeyo (parcours self-service) est seul
        responsable des résultats obtenus. Xeyo ne peut être tenu responsable d&apos;une mauvaise configuration autonome.
      </p>

      <h2>Article 6 – Connexion WhatsApp et responsabilité Meta</h2>
      <p>L&apos;Utilisateur reconnaît et accepte que :</p>
      <ul>
        <li>La connexion de son compte WhatsApp à Xeyo s&apos;effectue via l&apos;API officielle WhatsApp Business (Meta Cloud API)</li>
        <li>L&apos;utilisation de WhatsApp reste soumise aux Conditions d&apos;Utilisation de Meta/WhatsApp</li>
        <li>Meta/WhatsApp peut à tout moment suspendre ou fermer un compte en cas de violation de ses règles</li>
        <li>L&apos;envoi de messages automatisés, de spam ou de contenus non sollicités peut entraîner le bannissement du compte WhatsApp par Meta</li>
      </ul>

      <p>L&apos;Utilisateur s&apos;engage à :</p>
      <ul>
        <li>Respecter les Conditions d&apos;Utilisation de WhatsApp Business</li>
        <li>Ne pas utiliser les Services pour envoyer des messages non sollicités (spam)</li>
        <li>Obtenir le consentement préalable des destinataires pour les communications automatisées</li>
        <li>Respecter les limites de volume de messages imposées par WhatsApp</li>
      </ul>

      <div className="not-prose my-4 rounded-lg border-l-4 border-red-500 bg-red-50 p-4 dark:bg-red-950/30">
        <p className="font-medium text-slate-900 dark:text-white">Clause de non-responsabilité</p>
        <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">
          Xeyo ne saurait être tenue responsable de la suspension, limitation ou fermeture d&apos;un compte
          WhatsApp par Meta, quelle qu&apos;en soit la raison. Aucun remboursement ne sera effectué dans ce cas.
        </p>
      </div>

      <h2>Article 7 – Propriété intellectuelle</h2>
      <p>Xeyo conserve tous les droits de propriété intellectuelle sur les Services.</p>
      <p>L&apos;Utilisateur conserve tous les droits sur les contenus qu&apos;il crée ou uploade.</p>

      <h2>Article 8 – Responsabilité</h2>
      <p>Xeyo s&apos;engage à fournir les Services avec diligence (obligation de moyens).</p>
      <p>Xeyo ne saurait être tenue responsable :</p>
      <ul>
        <li>Des interruptions de service indépendantes de sa volonté</li>
        <li>Des contenus générés par l&apos;intelligence artificielle</li>
        <li>De la suspension ou fermeture de comptes WhatsApp par Meta</li>
        <li>Des préjudices indirects (perte de chiffre d&apos;affaires, etc.)</li>
        <li>Des résultats obtenus dans le cadre d&apos;un parcours self-service sans accompagnement</li>
      </ul>

      <h2>Article 9 – Suspension, résiliation et données</h2>
      <p>
        Xeyo peut suspendre ou résilier l&apos;accès aux Services, sans préavis, en cas de violation des présentes
        CGU, d&apos;utilisation frauduleuse ou abusive, de non-paiement ou de demande des autorités compétentes.
      </p>
      <p>
        À la résiliation ou suspension définitive, les données du client (conversations, agents, documents, base de
        connaissances) sont conservées pendant 30 jours, puis définitivement supprimées conformément au RGPD.
        Aucune récupération n&apos;est possible après ce délai.
      </p>

      <h2>Article 10 – Droit applicable</h2>
      <p>Les présentes CGU sont régies par le droit français.</p>
      <p>
        En cas de litige, les parties rechercheront une solution amiable. À défaut, les tribunaux français
        seront compétents.
      </p>
    </LegalPageLayout>
  )
}
